config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :contacts, only: :index
  resources :participating_schools, path: 'participating-schools'
  resources :companies
  resources :events do
    collection do
      get :map
    end
    member do
      post :approve
      post :unapprove
    end
  end
  resources :frequently_asked_questions, path: 'frequently-asked-questions'

  as :school do
    get 'schools/profile', to: 'devise/registrations#edit', as: :school_root
  end

  as :speaker do
    get 'speakers/profile', to: 'devise/registrations#edit', as: :speaker_root
  end

  devise_for :schools, controllers: {registrations: 'registrations'}
  devise_for :speakers, controllers: {registrations: 'registrations'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/controllers/participating_schools_controller.rb
class ParticipatingSchoolsController < ApplicationController
  def index
    @schools = School.participating.with_location_info.order('town_id, name')
  end

  def show
    @school = School.find(params[:id])
    @school_events = events_scope_for(@school).newest_first
    @pending_events_count = @school.pending_events.count(:all)
  end

  private

  def events_scope_for(school)
    if current_school == school
      school.events
    else
      school.events.approved
    end
  end
end

app/views/participating_schools/index.html.erb
<h1>Учебни заведения</h1>

<p>Списък на учебните заведения, които са изявили желание да се включат в Бъдещето е код.</p>

<% @schools.group_by(&:town).each do |town, schools| %>
  <h2><%= town.full_name %></h2>
  <ul class="schools">
    <% schools.sort_by { |school| [school.up_to_date? ? 0 : 1, school.name] }.each do |school| %>
      <li>
        <%= link_to participating_school_path(school) do %>
          <span class="name"><%= school.name %></span>
          <% if school.events.size > 0 %>
            <span class="label success"><%= pluralize school.events.size, 'събитие', 'събития' %></span>
          <% end %>
          <% if school.outdated? %>
            <span class="label error" title="Профилът не е обновяван от <%= time_ago_in_words school.updated_at %>">
              старо
            </span>
          <% end %>
          <span class="btn">виж детайли</span>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/participating_schools/show.html.erb
<h1>
  <%= @school.name %>
  <%= content_tag :small, 'не участва', class: 'label error' unless @school.confirmed_participation? %>
  <br>
  <small><%= @school.town.name_with_kind %></small>
</h1>

<% unless @school.confirmed_participation? %>
  <p>Учебното заведение <span class="label error">не участва</span> в текущото издание на инициативата.</p>
<% end %>

<p>Вижте <%= link_to 'списъка с всички учебни заведения', participating_schools_path %>.</p>

<h2>Събития</h2>
<% if @school_events.any? %>
  <ul>
    <% @school_events.each do |event| %>
      <li>
        <%= link_to event do %>
          <%= event.full_name_with_date %>
          <% if event_host_for?(event) && event.pending? %>
            <span class="label warning">очаква потвърждение</span>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>
    Все още няма потвърдени събития в това учебно заведение.
    <% if speaker_signed_in? %>
      <%= link_to 'Създайте събитие →', new_event_path(event: {school_id: @school.id}), class: 'btn' %>
    <% else %>
      <%= link_to 'Влезте като лектор', new_speaker_session_path %>, за да създадете събитие.
    <% end %>
  </p>
<% end %>
<% if @pending_events_count > 0 %>
  <p>
    В учебното заведение има
    <span class="label warning"><%= pluralize @pending_events_count, 'непотвърдено събитие.', 'непотвърдени събития.' %></span>
  </p>
<% end %>

<h2>Информация за учебното заведение</h2>
<ul class="details inline">
  <li>
    <label>Наименование:</label>
    <span class="value"><%= @school.name %></span>
  </li>
  <li>
    <label>Област:</label>
    <span class="value"><%= @school.state.name %></span>
  </li>
  <li>
    <label>Община:</label>
    <span class="value"><%= @school.municipality.name %></span>
  </li>
  <li>
    <label>Населено място:</label>
    <span class="value"><%= @school.town.name %></span>
  </li>
  <li>
    <label>Адрес:</label>
    <span class="value"><%= @school.address %></span>
  </li>
</ul>

<%= link_to_map_with_preview_for @school if @school.geocoded? %>

<h2>Информация за участие</h2>
<ul class="details">
  <li>
    <label>Актуална ли е информацията</label>
    <span class="value">
      <% if @school.up_to_date? %>
        Да, <span class="label success">актуална е</span>
      <% else %>
        Не, <span class="label error">остаряла е</span>
      <% end %>
      — профилът е обновен за последен път преди <%= time_ago_in_words @school.updated_at %>.
    </span>
  </li>
  <li>
    <label>Предмет/и</label>
    <ul>
      <% @school.disciplines.each do |option| %>
        <li><%= Options.translate(option, type: 'disciplines') %></li>
      <% end %>
    </ul>
  </li>
  <li>
    <label>Налична техника</label>
    <ul>
      <% @school.available_equipment.each do |option| %>
        <li><%= Options.translate(option, type: 'available_equipment') %></li>
      <% end %>
    </ul>
  </li>
  <li>
    <label>Възможност за организация на еднократната сбирка в извънучебно време</label>
    <span class="value">
      <%= Options.translate(@school.meetup_options, type: 'meetup_options') %>
    </span>
  </li>
  <li>
    <label>Дати за посещение</label>
    <span class="value"><%= simple_format @school.visit_dates %></span>
  </li>
  <% if @school.remarks.present? %>
    <li>
      <label>Забележки</label>
      <span class="value"><%= simple_format @school.remarks %></span>
    </li>
  <% end %>
</ul>

<h2>Лице за контакт</h2>
<% if speaker_signed_in? %>
  <ul class="details inline">
    <li>
      <label>Име:</label>
      <span class="value"><%= @school.contact_name %></span>
    </li>
    <li>
      <label>Телефон:</label>
      <span class="value"><%= @school.phone %></span>
    </li>
    <li>
      <label>Имейл адрес:</label>
      <span class="value"><%= mail_to @school.email %></span>
    </li>
  </ul>

  <h2>Събитие</h2>
  <p>Ако сте се свързали с лицето за контакт и сте уговорили посещение в учебното заведение, създайте събитие за посещението.</p>
  <p>
    <%= link_to 'Създайте събитие в това учебно заведение →', new_event_path(event: {school_id: @school.id}), class: 'btn' %>
  </p>
<% else %>
  <p>Влезте като лектор, за да видите данните за контакт за това учебно заведение и пълния му профил, както и за да може да създадете събитие.</p>
  <p><%= link_to 'Вход като лектор', new_speaker_session_path, class: 'btn' %></p>
<% end %>