config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :contacts, only: :index
  resources :participating_schools, path: 'participating-schools'
  resources :companies
  resources :events do
    collection do
      get :map
    end
    member do
      post :approve
      post :unapprove
    end
  end
  resources :frequently_asked_questions, path: 'frequently-asked-questions'

  as :school do
    get 'schools/profile', to: 'devise/registrations#edit', as: :school_root
  end

  as :speaker do
    get 'speakers/profile', to: 'devise/registrations#edit', as: :speaker_root
  end

  devise_for :schools, controllers: {registrations: 'registrations'}
  devise_for :speakers, controllers: {registrations: 'registrations'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @companies = Company.where(pledged_support: true)
    @participating_schools_count = School.participating.size
    @events = Event.all
  end
end

app/views/home/_companies_who_pledged_support.html.erb
<div class="pledged-support">
  <div class="content">
    <p class="joined">В инициативата участват</p>
    <ul class="companies">
      <% @companies.each do |company| %>
        <li>
          <% if company.url.present? %>
            <%= link_to company.url, target: '_blank', rel: 'nofollow', class: 'company' do %>
              <%= image_tag company.logo.url(:medium), alt: company.name, title: company.name %>
            <% end %>
          <% else %>
            <%= image_tag company.logo.url(:medium), alt: company.name, title: company.name %>
          <% end %>
        </li>
      <% end %>
    </ul>

    <p class="join-us">
      <%= link_to 'Включете се като фирма →', new_company_path, class: 'btn light' %>
    </p>
  </div>
</div>

app/views/home/index.html.erb
<div class="hero">
  <div class="content">
    <%= link_to root_path do %>
      <%= image_tag 'codeweekeu-icon.png', alt: 'Code Week', class: 'icon' %>
    <% end %>
    <h1>Бъдещето е код</h1>
    <p class="about">
      Турне на работещи в IT-сферата из училища в страната<br>
      Съвместно с <%= link_to 'Министерството на образованието и науката', 'https://mon.bg' %><br>
      <strong><%= ENV['CURRENT_PERIOD'] %></strong>
    </p>
    <p class="join-as">Включете се като</p>
    <p class="join-as-buttons">
      <%= link_to 'Училище', new_school_registration_path, class: 'btn' %>
      <%= link_to 'Лектор', new_speaker_registration_path, class: 'btn' %>
    </p>
    <p class="login">
      Имате регистрация? Влезте като <%= link_to 'училище', new_school_session_path %> или <%= link_to 'лектор', new_speaker_session_path %>.
    </p>
  </div>
</div>

<%= render 'companies_who_pledged_support' if @companies.any? %>

<div class="content-wrapper detailed-about">
  <div class="content article">
    <div class="details">
      <h3>Какво</h3>
      <p>Запалени мъже и жени, работещи в IT сектора, посещават избрано българско училище и в разговор с учениците разпалват интереса им към програмирането, дизайна и технологиите.</p>
    </div>

    <div class="organizers">
      <h3>Кой</h3>
      Организира се от <%= link_to 'Дигиталната национална коалиция', 'https://digitalalliance.bg' %> с помощта на екип от доброволци и със съдействието на <%= link_to 'Министерството на образованието', 'https://mon.bg' %> в периода <%= ENV['CURRENT_PERIOD'] %>.
    </div>

    <p class="inspire">Имаме нужда от вашия ентусиазъм, за да разкажете своите истории и да вдъхновите и може би да промените живота на младите хора.</p>
  </div>
</div>

<% if @participating_schools_count > 10 %>
  <div class="content-wrapper white-section participating-schools-wrapper">
    <div class="content article">
      <%= link_to participating_schools_path, class: 'participating-schools' do %>
        <strong><%= @participating_schools_count %></strong>
        учебни заведения от цялата страна участват
      <% end %>
      <%= link_to 'Включете се като учебно заведение →', new_school_registration_path, class: 'btn light' %>
      <p>Или <%= link_to 'вижте списък с участващите', participating_schools_path %>.</p>
    </div>
  </div>
<% end %>

<div class="content-wrapper speakers">
  <div class="content article">
    <h2>Запален програмист ли сте?</h2>
    <p>Вярвате ли, че да програмираш е безценно умение? Отделете един ден и посетете българско училище, за да разкажете на учениците защо.</p>
    <p>Вие избирате за какво да говорите, как да го оформите и в кое учебно заведение. Ние осигуряваме възможността официално да влезете в учебен час.</p>
    <p class="action">
      <%= link_to 'Включете се като лектор →', new_speaker_registration_path, class: 'btn light' %>
    </p>
  </div>
</div>

<% if @events.size > 5 %>
  <div class="content-wrapper promo-box events">
    <div class="content article">
      <p class="counter">
        <strong><%= @events.size %></strong>
        събития в цялата страна
      </p>

      <p class="action">
        <%= link_to 'Вижте всички събития', events_path, class: 'btn light' %>
      </p>
    </div>
  </div>
<% end %>

<div class="content-wrapper promo-box motivation">
  <div class="content article">
    <blockquote>
      "Осъзнах, че в училище съм си създала погрешна и ограничена представа за процеса на програмиране и това, което може да се постигне чрез него."
    </blockquote>

    <p>Да атакуваме рано предразсъдъците, че програмирането е скучно, сложно, само за специални хора и да покажем какво може да се постигне с тези умения.</p>

    <p class="action">
      <%= link_to 'Прочетете повече за мотивацията ни', frequently_asked_questions_path(anchor: 'motivation'), class: 'btn light' %>
    </p>
  </div>
</div>

<div class="content-wrapper promo-box more-info">
  <div class="content article">
    <h2>Често задавани въпроси</h2>
    <p>Имате нужда от повече подробности около инициативата, мотивацията ни, или логистиката? Искате да знаете кой стои зад кампанията и защо?</p>
    <p class="action">
      <%= link_to 'Вижте страницата с често задавани въпроси', frequently_asked_questions_path, class: 'btn light' %>
    </p>
  </div>
</div>

<%= render 'layouts/footer' %>