config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :contacts, only: :index
  resources :participating_schools, path: 'participating-schools'
  resources :companies
  resources :events do
    collection do
      get :map
    end
    member do
      post :approve
      post :unapprove
    end
  end
  resources :frequently_asked_questions, path: 'frequently-asked-questions'

  as :school do
    get 'schools/profile', to: 'devise/registrations#edit', as: :school_root
  end

  as :speaker do
    get 'speakers/profile', to: 'devise/registrations#edit', as: :speaker_root
  end

  devise_for :schools, controllers: {registrations: 'registrations'}
  devise_for :speakers, controllers: {registrations: 'registrations'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/event.rb
class Event < ActiveRecord::Base
  include DeletableAttachment

  belongs_to :speaker, counter_cache: true
  belongs_to :school, counter_cache: true

  has_attached_file :cover_image, styles: {
    large:  '1600x400>',
    medium: '1200x300>',
    small:  '800x200>',
    tiny:   '400x100>',
  }

  delegate :latitude, :longitude, :geocoded?, to: :school
  delegate :update_company_events_count, to: :speaker

  validates :speaker_id, presence: true
  validates :school_id, presence: true
  validates :date, presence: true
  validates :details, presence: true
  validates :cover_image, attachment_size: {less_than: 2.megabytes},
                          attachment_content_type: {content_type: /\Aimage\/.*\Z/},
                          dimensions: {min_width: 800, min_height: 100}
  validate  :school_does_not_change, if: :persisted?

  after_save :update_company_events_count

  scope :newest_first, -> { order(arel_table[:date].desc) }
  scope :approved, -> { where(approved: true) }
  scope :pending, -> { where(approved: false) }

  deletable_attachment :cover_image

  def name_or_default
    if name.present?
      name
    else
      default_name
    end
  end

  def name_or_school_name
    if name.present?
      name
    else
      school.name
    end
  end

  def default_name
    I18n.t('default_event_name', date: I18n.l(date), school: school.name)
  end

  def full_name_with_date
    "#{localized_date}, #{school.town.full_name} – #{name_or_school_name}"
  end

  def short_description
    description =
      if name.present?
        %Q(#{name} – събитие от "Бъдещето е код", провеждащо се на #{localized_date} в #{school.name_with_location})
      else
        %Q(Събитие от "Бъдещето е код", провеждащо се на #{localized_date} в #{school.name_with_location})
      end

    description << ", организирано от #{speaker.company_name}" if speaker.company_name.present?
    description << ", с лектор #{speaker.name}."

    description
  end

  def localized_date
    I18n.l date, format: '%d %B %Y г.'
  end

  def pending?
    !approved?
  end

  def as_json(options = {})
    {
      id: id,
      latitude: latitude,
      longitude: longitude,
      name: full_name_with_date,
    }
  end

  private

  def school_does_not_change
    if school_id_changed?
      errors.add :school_id, :cannot_change
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html

  before_filter :authenticate_speaker!, only: [:new, :create, :edit, :update]
  before_filter :authenticate_school!, only: [:approve, :unapprove]

  def index
    current_member = current_speaker || current_school
    @own_events = current_member.events.newest_first if current_member
    @events = Event.newest_first
  end

  def map
    @events = Event
      .newest_first
      .includes(:school)
      .select(&:geocoded?)
  end

  def new
    @event = Event.new default_event_params
  end

  def create
    @event = current_speaker.events.create event_params

    if @event.persisted?
      ApplicationMailer.new_event(@event).deliver_later
    end

    flash[:notice] = 'Събитието ви е създадено успешно и очаква преглед и одобрение от лицето за контакт в учебното заведение.'

    respond_with @event
  end

  def show
    @event = Event.find params[:id]
    @title = I18n.t('site.title', title: @event.name_or_default)
    @page_image = @event.cover_image.url(:large) if @event.cover_image.present?
    @page_description = @event.short_description
  end

  def edit
    @event = current_speaker.events.find params[:id]
  end

  def update
    @event = current_speaker.events.find params[:id]
    @event.update_attributes event_params

    respond_with @event
  end

  def approve
    event = current_school.events.find params[:id]
    event.update_attributes approved: true

    if event.errors.none?
      ApplicationMailer.event_approved(event).deliver_later
    end

    flash[:notice] = 'Събитието е одобрено.'

    redirect_to event
  end

  def unapprove
    event = current_school.events.find params[:id]
    event.update_attributes approved: false

    if event.errors.none?
      ApplicationMailer.event_reverted_to_pending(event).deliver_later
    end

    flash[:notice] = 'Събитието е върнато в състояние на очакващо потвърждение.'

    redirect_to event
  end

  private

  def event_params
    params.require(:event).permit(
      :school_id,
      :date,
      :name,
      :url,
      :public_email,
      :cover_image,
      :delete_cover_image,
      :details
    )
  end

  def default_event_params
    params
      .fetch(:event, {})
      .permit(:school_id)
      .merge(public_email: current_speaker.email, date: 1.week.from_now.to_date)
  end
end

app/views/events/_event_fields.html.erb
<% if form.object.persisted? %>
  <label>Учебно заведение</label>
  <%= link_to form.object.school.name_with_location, participating_school_path(form.object.school) %>
<% else %>
  <%= form.association :school, collection: School.participating.in_alphabetical_order.with_location_info, label_method: :name_with_location %>
<% end %>
<%= form.input :date, prompt: true %>
<%= form.input :name %>
<%= form.input :url %>
<%= form.input :public_email %>
<%= form.input :cover_image %>
<%= form.input :delete_cover_image, as: :boolean %>
<%= form.input :details %>

app/views/events/_instructions.html.erb
<p>Формуляр за посещение в учебно заведение, за което имате уговорка. Ако все още не сте избрали учебно заведение и не сте се свързали с лицето за контакт, прегледайте <%= link_to 'списъка с всички участващи учебни заведения', participating_schools_path %>.</p>

<p>След създаване на събитието, ще бъде необходимо то да бъде одобрено от учебното заведение. Лицето за контакт ще бъде автоматично известено по имейл, че има ново събитие, което чака одобрение. След одобрение, ще получите имейл. Ако събитието ви не бъде одобрено дълго време, свържете се с лицето за контакт в избраното учебно заведение, или с <%= link_to 'някой от нашия екип', contacts_path %>.</p>

<p>Можете да изпращате линка до новосъздаденото събитие, за да го популяризирате. Страницата ще бъде видима и преди одобрение от учебното заведение. Ще можете да редактирате данните на събитието и след създаването му.</p>

<p>За какво ще говорите зависи изцяло от вас. В раздела с <%= link_to 'често задавани въпроси имаме някои препоръки', frequently_asked_questions_path(anchor: 'content') %>.</p>

<p>Не забравяйте да направите снимки по време на събитието.</p>

app/views/events/edit.html.erb
<h1>Промяна на събитие</h1>

<%= render 'instructions' %>

<%= simple_form_for @event do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= render 'event_fields', form: f %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    или <%= link_to 'отказ и обратно към събитието', event_path(@event) %>
  </div>
<% end %>

app/views/events/index.html.erb
<h1>
  Събития
  <%= link_to 'вижте карта', map_events_path, class: 'btn light' %>
</h1>

<% if @own_events && @own_events.any? %>
  <div class="events">
    <h2>Моите събития</h2>
    <ul>
      <% @own_events.each do |event| %>
        <li>
          <%= link_to event do %>
            <%= event.full_name_with_date %>
            <% unless event.approved? %>
              <span class="label warning">чака потвърждение</span>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @events.any? %>
  <div class="events">
    <% @events.group_by { |event| l event.date, format: '%B, %Y' }.each do |month, events| %>
      <h2><%= month %></h2>
      <ul>
        <% events.each do |event| %>
          <li>
            <%= link_to event.full_name_with_date, event %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
<% else %>
  <p>Все още няма регистрирани събития.</p>
<% end %>

app/views/events/map.html.erb
<% content_for :top_section do %>
  <style type="text/css">
    body {
      background-color: #FFF;
    }
    .content-wrapper {
      padding-bottom: 1px;
    }
    #map {
      height: 300px;
    }
  </style>

  <div class="content-wrapper">
    <article>
      <h1>
        Събития
        <%= link_to 'вижте списък', events_path, class: 'btn light' %>
      </h1>
    </article>
  </div>

  <div id="map">
    <% if @events.none? %>
      <div class="content-wrapper">
        <div class="content article">
          <p>Все още няма събития.</p>
        </div>
      </div>
    <% end %>
  </div>

  <script type="text/javascript">
    $(function () {
      var events = <%= @events.to_json.html_safe %>;
      var $map = $('#map');

      if (events.length == 0) {
        return;
      }

      var resizeMap = function () {
        var height = $(window).height() - $('footer').outerHeight() - $('header').outerHeight() - $('.content-wrapper').outerHeight();
        height = Math.max(height, 300);
        $map.height(height);
      };

      var initializeMap = function () {
        $map.html('');

        var map = L.map('map', {
          scrollWheelZoom: false,
          trackResize: true,
          detectRetina: true
        });

        // Make sure all events are visible initially
        var bounds = new L.latLngBounds($.map(events, function (event) {
          return L.latLng(event.latitude, event.longitude);
        }));

        map.setView(bounds.getCenter(), 13);
        map.fitBounds(bounds);

        // Setup the map's layers
        L.tileLayer(<%= Leaflet.tile_layer.to_json.html_safe %>, {
            attribution: <%= Leaflet.attribution.to_json.html_safe %>,
            maxZoom: <%= Leaflet.max_zoom %>
        }).addTo(map);

        // Add all events as markers
        $.each(events, function () {
          var event = this;

          var eventLink = $('<a/>')
            .text(event.name)
            .attr('href', '/events/' + event.id);
          var eventLinkHtml = $('<div/>').append(eventLink).html();

          L.marker([event.latitude, event.longitude])
            .addTo(map)
            .bindPopup(eventLinkHtml);
        });
      };

      $(window).on('resize', resizeMap);

      resizeMap();
      initializeMap();
    });
  </script>
<% end %>

app/views/events/new.html.erb
<h1>Създаване на ново събитие</h1>

<%= render 'instructions' %>

<%= simple_form_for @event do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= render 'event_fields', form: f %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<% content_for :top_section do %>
  <div class="event-header <%= 'with-background' if @event.cover_image? %>" style="background-image: url(<%= @event.cover_image.url(:large) if @event.cover_image? %>);">
    <div class="content-wrapper">
      <div class="content">
        <h1><%= @event.name_or_default %></h1>
        <div class="school"><%= link_to @event.school.name, participating_school_path(@event.school) %></div>
        <div class="town"><%= l @event.date, format: '%d %B' %>, <%= @event.school.town.name_with_kind %></div>
        <% if @event.speaker.company_or_other.present? %>
          <div class="organizer">
            Организирано от <%= link_to_company @event.speaker.company_or_other %>
          </div>
        <% end %>
        <p><%= link_to 'Всички събития', events_path %></p>
      </div>
    </div>
  </div>
<% end %>

<div class="event">
  <% if event_host_for?(@event) %>
    <% if @event.approved? %>
      <p class="separated">
        Това събитие е <span class="label success">потвърдено</span> от вас.
        При нужда, може да го
        <%= link_to 'върнете в очакващо потвърждение', unapprove_event_path(@event), method: :post %>.
      </p>
    <% else %>
      <p class="separated">
        Това събитие <span class="label warning">очаква потвърждение</span> от вас.
        <%= link_to 'Потвърдете събитието', approve_event_path(@event), method: :post, class: 'btn' %>
      </p>
    <% end %>
  <% elsif @event.pending? %>
    <p class="separated">
      <span class="label warning">очаква потвърждение от учебното заведение</span>
    </p>
  <% end %>

  <ul class="details inline">
    <li>
      <label>Дата:</label>
      <span class="value"><%= l @event.date, format: '%d %B %Y г.' %></span>
    </li>
    <li>
      <label>Лектор:</label>
      <span class="value"><%= @event.speaker.name %></span>
    </li>
    <% if @event.public_email.present? %>
      <li>
        <label>Имейл за връзка:</label>
        <span class="value"><%= mail_to @event.public_email %></span>
      </li>
    <% end %>
    <% if event_host_for?(@event) %>
      <li>
        <label>Имейл на лектора:</label>
        <span class="value"><%= mail_to @event.speaker.email %> <small>(видим само за вас като домакин)</small></span>
      </li>
      <% if @event.speaker.phone.present? %>
        <li>
          <label>Телефон:</label>
          <span class="value"><%= @event.speaker.phone %> <small>(видим само за вас като домакин)</small></span>
        </li>
      <% end %>
    <% end %>
    <% if @event.url.present? %>
      <li>
        <label>Сайт:</label>
        <span class="value"><%= link_to truncate(@event.url, length: 50), @event.url, target: '_blank', rel: 'nofollow' %></span>
      </li>
    <% end %>
    <li>
      <label>Учебно заведение:</label>
      <span class="value"><%= link_to @event.school.name, participating_school_path(@event.school) %></span>
    </li>
    <li>
      <label>Адрес:</label>
      <span class="value"><%= @event.school.full_address %></span>
    </li>
  </ul>

  <%= link_to_map_with_preview_for @event.school %>

  <h2>Описание</h2>

  <div class="details">
    <%= markup @event.details %>
  </div>

  <% if speaker_signed_in? && current_speaker == @event.speaker %>
    <h2>Инструменти</h2>
    <p><%= link_to 'Редактирай събитието', edit_event_path(@event), class: 'btn' %></p>
  <% end %>
</div>