config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :contacts, only: :index
  resources :participating_schools, path: 'participating-schools'
  resources :companies
  resources :events do
    collection do
      get :map
    end
    member do
      post :approve
      post :unapprove
    end
  end
  resources :frequently_asked_questions, path: 'frequently-asked-questions'

  as :school do
    get 'schools/profile', to: 'devise/registrations#edit', as: :school_root
  end

  as :speaker do
    get 'speakers/profile', to: 'devise/registrations#edit', as: :speaker_root
  end

  devise_for :schools, controllers: {registrations: 'registrations'}
  devise_for :speakers, controllers: {registrations: 'registrations'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/views/layouts/_alerts.html.erb
<% if notice.present? or alert.present? %>
  <div class="alerts">
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_analytics.html.erb
<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55595857-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_captcha.html.erb
<%- validation_error = model.errors[:captcha].to_sentence if model && model.respond_to?(:errors) -%>

<%= recaptcha_tags hl: 'bg' %>

<%- unless validation_error.blank? -%>
<span class="error"><%= validation_error %></span>
<%- end -%>

app/views/layouts/_footer.html.erb
<footer>
  <div class="social-links">
    <div class="content">
      <ul>
        <li>
          <%= link_to ENV['FACEBOOK_PAGE_URL'] do %>
            <i class="fa fa-facebook"></i>
            futureiscode
          <% end %>
        </li>
        <li>
          <%= link_to ENV['TWITTER_URL'] do %>
            <i class="fa fa-twitter"></i>
            @futureiscode
          <% end %>
        </li>
        <li>
          <%= mail_to ENV['CONTACT_EMAIL_ADDRESS'] do %>
            <i class="fa fa-envelope-o"></i>
            <%= ENV['CONTACT_EMAIL_ADDRESS'] %>
          <% end %>
        </li>
        <li>
          <%= link_to contacts_path do %>
            <i class="fa fa-phone"></i>
            контакти
          <% end %>
        </li>
      </ul>
    </div>
  </div>

  <div class="footer-details">
    <div class="content">
      <h4>Относно "Бъдещето е код"</h4>

      <p>
        Инициатива, организирана от <%= link_to 'Дигиталната национална коалиция', 'https://digitalalliance.bg' %>
        и <%= link_to 'посланика на Europe Code Week за България', 'https://ddimitrov.name' %>,
        със съдействието на <%= link_to 'Министерството на образованието', 'https://mon.bg' %>,
        <%= link_to 'Регионалните инспекторати по образованието', 'https://www.riobg.com/selectrio' %>,
        ръководството и учителите в участващите учебни заведения и множество доброволци. Научете повече в секцията с <%= link_to 'често задавани въпроси', frequently_asked_questions_path %> или се <%= link_to 'свържете с нас', contacts_path %>.
      </p>

      <h4>За сайта</h4>

      <p>
        Този сайт е с <%= link_to 'отворен код', ENV['SITE_REPO_URL'] %>.
        Използвани са снимки на <%= link_to 'Радослав Георгиев', 'https://github.com/RadoRado', target: '_blank' %>.
        Съдържанието е под лиценз <%= link_to 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0/', target: '_blank', rel: 'nofollow' %>.
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width">

<title><%= @title || t('site.default_title') %></title>
<meta name="description" content="<%= @page_description || t('site.default_description') %>">
<meta property="og:title" content="<%= @title || t('site.default_title') %>">
<meta property="og:description" content="<%= @page_description || t('site.default_description') %>" />
<% if @page_image %>
  <meta property="og:image" content="<%= @page_image %>">
<% end %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

app/views/layouts/_header.html.erb
<header>
  <div class="content">
    <%= link_to root_path, class: 'home-link' do %>
      <%= image_tag 'codeweekeu-icon.png', alt: 'Code Week', class: 'icon' %>
      Бъдещето е код
    <% end %>

    <div class="period"><%= ENV['CURRENT_PERIOD'] %></div>

    <% if school_signed_in? %>
      <div class="member-links">
        Здравейте, <%= link_to current_school.contact_name, edit_school_registration_path, title: 'Редакция на профила ви' %>.
        <%= link_to 'Изход', destroy_school_session_path, method: :delete %>
      </div>
    <% elsif speaker_signed_in? %>
      <div class="member-links">
        Здравейте, <%= link_to current_speaker.name, edit_speaker_registration_path, title: 'Редакция на профила ви' %>.
        <%= link_to 'Изход', destroy_speaker_session_path, method: :delete %>
      </div>
    <% else %>
      <div class="join">
        <%= link_to 'Лектор', new_speaker_registration_path, class: 'btn' %>
        <%= link_to 'Училище', new_school_registration_path, class: 'btn' %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <%= render 'layouts/head' %>
</head>
<body>
  <div class="page">
    <%= render 'layouts/header' %>
    <%= render 'layouts/alerts' %>
    <%= yield :top_section if content_for?(:top_section) %>

    <div class="content-wrapper">
      <article>
        <%= yield %>
      </article>
    </div>

    <div class="footer-placeholder"></div>
  </div>

  <%= render 'layouts/footer' %>
  <%= render 'layouts/analytics' %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <%= render 'layouts/head' %>
</head>
<body class="home">
  <%= render 'layouts/header' if member_signed_in? %>
  <%= render 'layouts/alerts' %>

  <%= yield %>

  <%= render 'layouts/analytics' %>
</body>
</html>